from PyQt5 import QtWidgets,QtGui
# d1=QtGui.QPixmap("bear.jpg")
app=QtWidgets.QApplication([])
# a=QtGui.QGuiApplication()
dia=QtWidgets.QDialog()
s=QtWidgets.QVBoxLayout()
p=QtWidgets.QHBoxLayout()
# dia.setWindowTitle("python")
# label=QtWidgets.QLabel(app)
# pix=QtGui.QPixmap('http://2.bp.blogspot.com/-BnJqpo8DJHk/UOmf9elav-I/AAAAAAAAML8/8fJWdAXZ9Nk/s1600/Portugal-vs-Turkey-cristiano-ronaldo-1499617-1076-1372.jpg')
# name.setPixmap(pix)
# s.addWidget(name)
b=QtWidgets.QPushButton("sum")
s.addStretch()
b1=QtWidgets.QPushButton("Sub")
p.addStretch()
s.addWidget(b1)
p.addStretch()
p.addWidget(b)
p.addStretch()
b2=QtWidgets.QPushButton("Bhature Frands")
b3=QtWidgets.QPushButton("Kachori Frands")
p.addWidget(b2)
p.addStretch()
p.addWidget(b3)
s.addLayout(p)
dia.setLayout(s)
# p=QtWidgets.QGraphicsPixmapItem("")
# pixmap=QtGui.QPixmap("bear.jpg")

# s.addWidget(name)
# s.addWidget(name1)
# s.addWidget(name2)
dia.setWindowTitle("Calculator")
dia.show()
app.exec_()